Add missing publish test
Without 15bef5f, this test fails just like in production::

    ERROR    django.request:log.py:224 Internal Server Error: /en/contest/6899fb1f-17ca-429e-a8e0-ff32e7031d5b/publish/
    Traceback (most recent call last):
      File "/home/jpic/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
        response = get_response(request)
      File "/home/jpic/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/home/jpic/.local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
        return view_func(request, *args, **kwargs)
      File "/home/jpic/.local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
        return self.dispatch(request, *args, **kwargs)
      File "/home/jpic/.local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
        return handler(request, *args, **kwargs)
      File "/home/jpic/.local/lib/python3.9/site-packages/django/views/generic/edit.py", line 194, in post
        return super().post(request, *args, **kwargs)
      File "/home/jpic/.local/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
        return self.form_valid(form)
      File "/home/jpic/src/electeez/djelectionguard/views.py", line 451, in form_valid
        self.object.publish()
      File "/home/jpic/src/electeez/djelectionguard/models.py", line 207, in publish
        from electionguard.tally import publish_ciphertext_tally
    ImportError: cannot import name 'publish_ciphertext_tally' from 'electionguard.tally'

This will prevent new EG releases that break the publish code from
being deployed.